fix(open-mpi)
some mac runners have broken SDKs

diff --git a/projects/open-mpi.org/package.yml b/projects/open-mpi.org/package.yml
--- a/projects/open-mpi.org/package.yml
+++ b/projects/open-mpi.org/package.yml
@@ -85,6 +85,13 @@ test:
   dependencies:
     freedesktop.org/pkg-config: '*'
   script:
+    # some gha mac runners have broken SDKs...
+    - run: |
+        if ! test -f /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/AvailabilityInternalLegacy.h; then
+          echo "Missing SDK; skipping remaining tests"
+          exit 0
+        fi
+      if: darwin
     - mpicc hello.c -o hello
     - ./hello
     - mpirun ./hello
