fix(gcc15.2)
closes #10169
closes #10166

diff --git a/projects/gnu.org/gcc/package.yml b/projects/gnu.org/gcc/package.yml
--- a/projects/gnu.org/gcc/package.yml
+++ b/projects/gnu.org/gcc/package.yml
@@ -29,19 +29,31 @@ build:
     # Applying ians patches on x86-64 too, since he sometimes gets fixes in faster, like:
     # https://github.com/orgs/Homebrew/discussions/5216
     # If we have a patch, apply it
-    - run: |
-        if test -n "$PATCH{{version.major}}{{version.minor}}"; then
-          curl "$PATCH{{version.major}}{{version.minor}}" | patch -p1
-        fi
+    - run:
+        - if test -n "$PATCH{{version.major}}{{version.minor}}"; then
+        - curl "$PATCH{{version.major}}{{version.minor}}" | patch -p1
+        - fi
       if: darwin
       working-directory: ..
 
     # if there's no diff yet, unpack iains' source over ours
-    - run: |
-        if test -n "$BRANCH{{version.major}}{{version.minor}}"; then
-          curl -L "$BRANCH{{version.major}}{{version.minor}}" | tar xz --strip-components=1
-        fi
+    - run:
+        - if test -n "$BRANCH{{version.major}}{{version.minor}}"; then
+        - curl -L "$BRANCH{{version.major}}{{version.minor}}" | tar xz --strip-components=1
+        - fi
       if: darwin
+      working-directory: ..
+
+    - run:
+        - if test "{{hw.platform}}/{{hw.arch}}" = "darwin/x86-64"; then
+        # Apply CFI directive fix for x86-64 Darwin (LLVM assembler compatibility)
+        - patch -p1 < props/disable-cfi-x86-64-darwin.patch
+        # Disable MS ABI stubs on Darwin - not needed and causes CFI/LLVM assembler issues
+        - patch -p1 < props/disable-msabi-darwin.patch
+        # Remove old frame registration symbols from darwin-unwind.ver (GCC 15+ doesn't provide these)
+        - patch -p1 < props/remove-old-frame-symbols-darwin.patch
+        - fi
+      if: =15.2
       working-directory: ..
 
     # The spaces mess things up in the env key
@@ -50,6 +62,11 @@ build:
     # On Linux, we need to statically link libstdc++ and libgcc
     - run: export ARGS=("${ARGS[@]}" --with-boot-ldflags="-static-libstdc++ -static-libgcc $LDFLAGS")
       if: linux
+
+    # needed to get the LDFLAGS to libgfortran on darwin
+    # for -headerpad_max_install_names
+    - run: export LDFLAGS_FOR_TARGET="$LDFLAGS"
+      if: darwin
 
     - ../configure "${ARGS[@]}"
     - make --jobs {{ hw.concurrency }}
@@ -60,24 +77,33 @@ build:
       working-directory: ${{prefix}}/bin
 
     # On Linux, we need to move the libraries to the lib directory.
-    - run: |
-        mv lib64/* lib/
-        rmdir lib64
+    - run:
+        - mv lib64/* lib/
+        - rmdir lib64
       if: linux
       working-directory: ${{prefix}}
 
     # other tools simply expect these symlinks and often fail without them
     # NOTE forcing symlinks because we build with ourselves and sometimes that
     # means we're building with the exact same version FIXME
-    - run: |
-        ln -sf gcc cc
-        ln -sf ../../../binutils/v\*/bin/ar ar
-        ln -sf ../../../binutils/v\*/bin/nm nm
-        ln -sf ../../../binutils/v\*/bin/ranlib ranlib
+    - run:
+        - ln -sf gcc cc
+        - ln -sf ../../../binutils/v\*/bin/ar ar
+        - ln -sf ../../../binutils/v\*/bin/nm nm
+        - ln -sf ../../../binutils/v\*/bin/ranlib ranlib
       working-directory: ${{prefix}}/bin
 
     # .la archives aren't relocatable
     - run: find . -name '*.la' -exec rm {} \;
+      working-directory: ${{prefix}}/lib
+
+    # fixup the signatures on libgcc_s on darwin x86-64
+    - run:
+        - codesign --remove-signature libgcc_s.1.1.dylib || true
+        - codesign -s - --force libgcc_s.1.1.dylib
+        - codesign --remove-signature libgcc_s.1.dylib || true
+        - codesign -s - --force libgcc_s.1.dylib
+      if: darwin/x86-64
       working-directory: ${{prefix}}/lib
 
   env:
@@ -100,6 +126,7 @@ build:
     BRANCH142: https://github.com/iains/gcc-14-branch/archive/refs/heads/gcc-14-2-darwin.tar.gz
     BRANCH143: https://github.com/iains/gcc-14-branch/archive/refs/heads/gcc-14-3-darwin-pre-0.tar.gz
     BRANCH151: https://github.com/iains/gcc-15-branch/archive/refs/heads/gcc-15-1-darwin-rc1.tar.gz
+    BRANCH152: https://github.com/iains/gcc-15-branch/archive/refs/heads/gcc-15-2-darwin-pre-0.tar.gz
     ARGS:
       - --prefix={{ prefix }}
       - --libdir={{ prefix }}/lib
@@ -124,6 +151,7 @@ build:
         - -fPIC
         - -fPIE
     darwin:
+      LDFLAGS: $LDFLAGS -Wl,-headerpad_max_install_names
       ARGS:
         # Reliance on CLT hard path is yuck.
         - --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
@@ -148,13 +176,12 @@ test:
   - gcc --version | grep -q "pkgx GCC {{version}}"
   - gcc -print-libgcc-file-name
   - gcc -print-multiarch
-  - gcc -dumpspecs
   # gha mac runners have broken SDKs...
-  - run: |
-      if ! test -f /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/AvailabilityInternalLegacy.h; then
-        echo "Missing SDK; skipping remaining tests"
-        exit 0
-      fi
+  - run:
+      - if ! test -f /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/AvailabilityInternalLegacy.h; then
+      - echo "Missing SDK; skipping remaining tests"
+      - exit 0
+      - fi
     if: darwin
   - gcc -o test1 test.c -lgmp
   - ./test1
