failure case

diff --git a/projects/tea.xyz/gx/cc/ld b/projects/tea.xyz/gx/cc/ld
--- a/projects/tea.xyz/gx/cc/ld
+++ b/projects/tea.xyz/gx/cc/ld
@@ -15,6 +15,9 @@ if which "$exe" 2>&1; then
 # (invoking `ld` as `lld64.ld`) watch for those potential cases
 elif which ld 2>&1; then
   exe=$(which ld)
+else
+  echo 'ld not found in PATH' >&2
+  exit 127
 fi
 
 if test -z "$TEA_PREFIX"
