[wip] Add test

diff --git a/projects/github.com/facebook/wangle/package.yml b/projects/github.com/facebook/wangle/package.yml
--- a/projects/github.com/facebook/wangle/package.yml
+++ b/projects/github.com/facebook/wangle/package.yml
@@ -51,46 +51,58 @@ test:
   dependencies:
     tea.xyz/gx/cc: c99
   script: |
-    # cxx_flags = %W[
-    #   -std=c++17
-    #   -I#{include}
-    #   -I#{Formula["openssl@1.1"].opt_include}
-    #   -L#{Formula["gflags"].opt_lib}
-    #   -L#{Formula["glog"].opt_lib}
-    #   -L#{Formula["folly"].opt_lib}
-    #   -L#{Formula["fizz"].opt_lib}
-    #   -L#{lib}
-    #   -lgflags
-    #   -lglog
-    #   -lfolly
-    #   -lfizz
-    #   -lwangle
-    # ]
-    # if OS.linux?
-    #   cxx_flags << "-L#{Formula["boost"].opt_lib}"
-    #   cxx_flags << "-lboost_context-mt"
-    #   cxx_flags << "-ldl"
-    #   cxx_flags << "-lpthread"
-    # end
+    c++ $CXXFLAGS 'EchoClient.cpp' -o EchoClient
+    c++ $CXXFLAGS 'EchoServer.cpp' -o EchoServer
 
-    # system ENV.cxx, pkgshare/"EchoClient.cpp", *cxx_flags, "-o", "EchoClient"
-    # system ENV.cxx, pkgshare/"EchoServer.cpp", *cxx_flags, "-o", "EchoServer"
+    # Find a free port
+    FREE_PORT=0
+    while :; do
+        FREE_PORT=$(shuf -i 49152-65535 -n 1)
+        if ! (nc -z 127.0.0.1 ${FREE_PORT}) 2>/dev/null; then
+            break
+        fi
+    done
 
-    # port = free_port
-    # fork { exec testpath/"EchoServer", "-port", port.to_s }
-    # sleep 10
+    # Start the EchoServer
+    ./EchoServer -port "${FREE_PORT}" &
+    SERVER_PID=$!
+    sleep 10
 
-    # require "pty"
-    # output = ""
-    # PTY.spawn(testpath/"EchoClient", "-port", port.to_s) do |r, w, pid|
-    #   w.write "Hello from Homebrew!\nAnother test line.\n"
-    #   sleep 20
-    #   Process.kill "TERM", pid
-    #   begin
-    #     r.each_line { |line| output += line }
-    #   rescue Errno::EIO
-    #     # GNU/Linux raises EIO when read is done on closed pty
-    #   end
-    # end
-    # assert_match("Hello from Homebrew!", output)
-    # assert_match("Another test line.", output)
+    # Run the EchoClient and interact with the EchoServer
+    OUTPUT_FILE=output.txt
+    rm -f "${OUTPUT_FILE}"
+    mkfifo "${OUTPUT_FILE}"
+    cat > "${OUTPUT_FILE}" &
+    CLIENT_BACKGROUND_PID=$!
+
+    # Send test lines to the EchoClient
+    ./EchoClient -port "${FREE_PORT}" > "${OUTPUT_FILE}" << EOF
+    Hello from tea!
+    Another test line.
+    EOF
+
+    sleep 20
+
+    # Kill the EchoServer and EchoClient
+    kill "${SERVER_PID}"
+    kill "${CLIENT_BACKGROUND_PID}"
+
+    # Check the output for the test lines
+    grep -q "Hello from Homebrew!" "${OUTPUT_FILE}"
+    grep -q "Another test line." "${OUTPUT_FILE}"
+
+    # Cleanup
+    rm -f "${OUTPUT_FILE}"
+  env:
+    CXXFLAGS:
+      - -std=c++17
+      - -lgflags
+      - -lglog
+      - -lfolly
+      - -lfizz
+      - -lwangle
+    linux:
+      CXXFLAGS:
+       - -lboost_context-mt
+       - -ldl
+       - -lpthread
