fix(cephadm)[3]

diff --git a/projects/ceph.com/cephadm/package.yml b/projects/ceph.com/cephadm/package.yml
--- a/projects/ceph.com/cephadm/package.yml
+++ b/projects/ceph.com/cephadm/package.yml
@@ -28,6 +28,21 @@ build:
     - mkdir -p {{prefix}}/bin
     - run: ./build.sh $BUILD_FLAGS {{prefix}}/bin/cephadm
       working-directory: src/cephadm
+    - run:
+        # because this is a packed zip archive, and hardcodes the path to python3
+        # we have to change the shebang to /usr/bin/env python3
+        # and pad it with # to keep the length the same
+        - shebang_length=$(head -n 1 {{prefix}}/bin/cephadm | wc -c)
+        - new_shebang="#!/usr/bin/env python3"
+        - padding_length=$((shebang_length - ${#new_shebang}))
+        - |
+          if [ $padding_length -lt 0 ]; then
+            echo "Error: New shebang is too long!" >&2
+            exit 1
+          fi
+        - padding=$(printf '%*s' "$padding_length" '' | tr ' ' '#')
+        - sed -i "1s|^#!.*$|${new_shebang}${padding}|" cephadm
+      working-directory: ${{prefix}}/bin
 
 provides:
   - bin/cephadm
