wip

diff --git a/projects/python.org/package.yml b/projects/python.org/package.yml
--- a/projects/python.org/package.yml
+++ b/projects/python.org/package.yml
@@ -132,6 +132,31 @@ build:
             # be assumed that no additional -I,-L directives are needed.
 
 test:
-  #TODO test all modules eg zlib module
   script: |
-    python --version
+    # Check if sqlite is ok, because we build with --enable-loadable-sqlite-extensions
+    # and it can occur that building sqlite silently fails if OSX's sqlite is used.
+    python -c "import sqlite3"
+
+    # check to see if we can create a venv
+    python -m venv myvenv
+
+    # Check if some other modules import. Then the linked libs are working.
+    python -c "import _ctypes"
+    # python -c "import _decimal" #FIXME
+    python -c "import pyexpat"
+    python -c "import zlib"
+
+    # Verify that the selected DBM interface works
+    python $FIXTURE
+
+    if which pip; then
+      exit 1
+    fi
+  fixture: |
+    import dbm
+    with dbm.ndbm.open("test", "c") as db:
+        db[b"foo \\xbd"] = b"bar \\xbd"
+    with dbm.ndbm.open("test", "r") as db:
+        assert list(db.keys()) == [b"foo \\xbd"]
+        assert b"foo \\xbd" in db
+        assert db[b"foo \\xbd"] == b"bar \\xbd"
