Added script tag in test

diff --git a/projects/pokt.network/package.yml b/projects/pokt.network/package.yml
--- a/projects/pokt.network/package.yml
+++ b/projects/pokt.network/package.yml
@@ -20,9 +20,10 @@ build:
     mkdir -p "{{ prefix }}"/bin
     mv pocket "{{ prefix }}"/bin
 
-test: |
-  pocket --help >> /tmp/pocket.help
-  if ! grep -q "Pocket is a distributed network that relays data" /tmp/pocket.help; then
-    echo "Error: Pocket was not installed successfully"
-    exit 1
-  fi
+test:
+  script: |
+    pocket --help >> /tmp/pocket.help
+    if ! grep -q "Pocket is a distributed network that relays data" /tmp/pocket.help; then
+      echo "Error: Pocket was not installed successfully"
+      exit 1
+    fi
